namespace ExpatOne.Application.DTOs;

public class ReminderDto
{
    public Guid Id { get; set; }
    public Guid DocumentId { get; set; }
    public required string DocumentName { get; set; }
    public required string DocumentType { get; set; }
    public DateTime? DocumentExpiryDate { get; set; }
    public required string Title { get; set; }
    public string? Description { get; set; }
    public DateTime ReminderDate { get; set; }
    public int DaysBeforeExpiry { get; set; }
    public required string Status { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; }
}

public class CreateReminderDto
{
    public Guid DocumentId { get; set; }
    public int DaysBeforeExpiry { get; set; }
}

public class UpdateReminderDto
{
    public string? Status { get; set; }
}

public class GenerateRemindersDto
{
    public Guid DocumentId { get; set; }
    public List<int> DaysBeforeExpiry { get; set; } = new();
}
