import '../networking/api_client.dart';

class ReminderItem {
  final String id;
  final String documentId;
  final String documentName;
  final String documentType;
  final DateTime? documentExpiryDate;
  final String title;
  final String? description;
  final DateTime reminderDate;
  final int daysBeforeExpiry;
  final String status;
  final bool isAutoGenerated;
  final DateTime createdAt;

  const ReminderItem({
    required this.id,
    required this.documentId,
    required this.documentName,
    required this.documentType,
    this.documentExpiryDate,
    required this.title,
    this.description,
    required this.reminderDate,
    required this.daysBeforeExpiry,
    required this.status,
    required this.isAutoGenerated,
    required this.createdAt,
  });

  factory ReminderItem.fromJson(Map<String, dynamic> json) => ReminderItem(
        id: json['id'] as String,
        documentId: json['documentId'] as String,
        documentName: json['documentName'] as String? ?? '',
        documentType: json['documentType'] as String? ?? '',
        documentExpiryDate: json['documentExpiryDate'] != null
            ? DateTime.parse(json['documentExpiryDate'] as String)
            : null,
        title: json['title'] as String,
        description: json['description'] as String?,
        reminderDate: DateTime.parse(json['reminderDate'] as String),
        daysBeforeExpiry: (json['daysBeforeExpiry'] as num?)?.toInt() ?? 0,
        status: json['status'] as String? ?? 'Active',
        isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
        createdAt: DateTime.parse(json['createdAt'] as String),
      );

  bool get isDue => reminderDate.isBefore(DateTime.now());
  bool get isActive => status == 'Active';
}

class ReminderService {
  final ApiClient _apiClient;

  ReminderService(this._apiClient);

  Future<List<ReminderItem>> getReminders() async {
    final response = await _apiClient.getList('/reminders');
    return response.map((e) => ReminderItem.fromJson(e)).toList();
  }

  Future<List<ReminderItem>> getDocumentReminders(String documentId) async {
    final response = await _apiClient.getList('/reminders/document/$documentId');
    return response.map((e) => ReminderItem.fromJson(e)).toList();
  }

  Future<List<ReminderItem>> generateReminders(String documentId, List<int> daysBeforeExpiry) async {
    final response = await _apiClient.post('/reminders/generate', body: {
      'documentId': documentId,
      'daysBeforeExpiry': daysBeforeExpiry,
    });
    // Response is an array
    if (response.isEmpty) return [];
    return [ReminderItem.fromJson(response)];
  }

  // Sends the generation POST only. Throws on failure — caller must treat any
  // exception as a save failure. Uses postVoid because the endpoint returns a
  // JSON array, which post() cannot cast to Map<String, dynamic>.
  Future<void> generateOnly(String documentId, List<int> daysBeforeExpiry) async {
    await _apiClient.postVoid('/reminders/generate', body: {
      'documentId': documentId,
      'daysBeforeExpiry': daysBeforeExpiry,
    });
  }

  Future<List<ReminderItem>> generateRemindersFromList(String documentId, List<int> daysBeforeExpiry) async {
    await _apiClient.post('/reminders/generate', body: {
      'documentId': documentId,
      'daysBeforeExpiry': daysBeforeExpiry,
    });
    final updated = await _apiClient.getList('/reminders/document/$documentId');
    return updated.map((e) => ReminderItem.fromJson(e)).toList();
  }

  Future<void> dismissReminder(String reminderId) async {
    await _apiClient.put('/reminders/$reminderId', body: {'status': 'Dismissed'});
  }

  Future<void> cancelReminder(String reminderId) async {
    await _apiClient.put('/reminders/$reminderId', body: {'status': 'Cancelled'});
  }

  Future<void> deleteReminder(String reminderId) async {
    await _apiClient.delete('/reminders/$reminderId');
  }
}
