import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:expatone_app/core/networking/api_client.dart';
import 'package:expatone_app/core/services/reminder_service.dart';
import 'package:expatone_app/features/reminders/reminders_screen.dart';
import 'package:expatone_app/features/reminders/manage_reminders_screen.dart';
import 'package:expatone_app/core/services/document_service.dart';

class MockReminderService extends ReminderService {
  List<ReminderItem> mockReminders = [];
  bool shouldFail = false;
  bool dismissCalled = false;

  // BUG-4 controls: independently fault the POST and GET stages.
  bool generateOnlyShouldFail = false;
  bool getDocumentRemindersShouldFail = false;
  int generateOnlyCallCount = 0;

  MockReminderService() : super(ApiClient());

  @override
  Future<List<ReminderItem>> getReminders() async {
    if (shouldFail) throw Exception('Failed');
    return mockReminders;
  }

  @override
  Future<List<ReminderItem>> getDocumentReminders(String documentId) async {
    if (shouldFail || getDocumentRemindersShouldFail) throw Exception('Failed');
    return mockReminders.where((r) => r.documentId == documentId).toList();
  }

  @override
  Future<void> dismissReminder(String reminderId) async {
    dismissCalled = true;
    if (shouldFail) throw Exception('Failed');
  }

  @override
  Future<void> generateOnly(String documentId, List<int> daysBeforeExpiry) async {
    generateOnlyCallCount++;
    if (generateOnlyShouldFail) throw Exception('Generation failed');
  }

  @override
  Future<List<ReminderItem>> generateRemindersFromList(
      String documentId, List<int> daysBeforeExpiry) async {
    return [];
  }
}

void main() {
  late MockReminderService reminderService;

  setUp(() {
    reminderService = MockReminderService();
  });

  group('RemindersScreen', () {
    testWidgets('shows empty state when no reminders', (tester) async {
      await tester.pumpWidget(MaterialApp(
        home: RemindersScreen(reminderService: reminderService),
      ));
      await tester.pumpAndSettle();

      expect(find.text('No active reminders'), findsOneWidget);
    });

    testWidgets('shows reminder list', (tester) async {
      reminderService.mockReminders = [
        ReminderItem(
          id: '1',
          documentId: 'd1',
          documentName: 'My Passport',
          documentType: 'Passport',
          documentExpiryDate: DateTime(2027, 6, 30),
          title: 'Passport expires in 30 days',
          reminderDate: DateTime(2027, 5, 31),
          daysBeforeExpiry: 30,
          status: 'Active',
          isAutoGenerated: true,
          createdAt: DateTime(2024, 1, 1),
        ),
      ];

      await tester.pumpWidget(MaterialApp(
        home: RemindersScreen(reminderService: reminderService),
      ));
      await tester.pumpAndSettle();

      expect(find.text('My Passport'), findsOneWidget);
      expect(find.text('Passport'), findsOneWidget);
      expect(find.text('30 days before expiry'), findsOneWidget);
      expect(find.text('Dismiss'), findsOneWidget);
    });

    testWidgets('shows error state', (tester) async {
      reminderService.shouldFail = true;

      await tester.pumpWidget(MaterialApp(
        home: RemindersScreen(reminderService: reminderService),
      ));
      await tester.pumpAndSettle();

      expect(find.text('Unable to load reminders'), findsOneWidget);
      expect(find.text('Retry'), findsOneWidget);
    });

    testWidgets('shows loading state', (tester) async {
      await tester.pumpWidget(MaterialApp(
        home: RemindersScreen(reminderService: reminderService),
      ));

      expect(find.byType(CircularProgressIndicator), findsOneWidget);
    });
  });

  group('ManageRemindersScreen', () {
    testWidgets('shows no-expiry message for doc without expiry', (tester) async {
      final doc = DocumentItem(
        id: '1', name: 'Letter', documentType: 'Other', documentTypeId: '9',
        fileSizeBytes: 100, status: 'Active', createdAt: DateTime(2024),
      );

      await tester.pumpWidget(MaterialApp(
        home: ManageRemindersScreen(document: doc, reminderService: reminderService),
      ));
      await tester.pumpAndSettle();

      expect(find.text('No expiry date'), findsOneWidget);
    });

    testWidgets('shows offset checkboxes for doc with expiry', (tester) async {
      final doc = DocumentItem(
        id: '1', name: 'Passport', documentType: 'Passport', documentTypeId: '1',
        fileSizeBytes: 100, status: 'Active', createdAt: DateTime(2024),
        expiryDate: DateTime.now().add(const Duration(days: 365)),
      );

      await tester.pumpWidget(MaterialApp(
        home: ManageRemindersScreen(document: doc, reminderService: reminderService),
      ));
      await tester.pumpAndSettle();

      expect(find.text('30 days before'), findsOneWidget);
      expect(find.text('14 days before'), findsOneWidget);
      expect(find.text('7 days before'), findsOneWidget);
      expect(find.text('1 days before'), findsOneWidget);
      expect(find.text('Save Reminders'), findsOneWidget);
    });
  });

  group('ManageRemindersScreen BUG-4 — POST/GET split', () {
    late DocumentItem docWithExpiry;

    setUp(() {
      docWithExpiry = DocumentItem(
        id: 'doc-bug4',
        name: 'Passport',
        documentType: 'Passport',
        documentTypeId: '1',
        fileSizeBytes: 100,
        status: 'Active',
        createdAt: DateTime(2024),
        expiryDate: DateTime.now().add(const Duration(days: 365)),
      );
    });

    // Builds the subject inside a tall MaterialApp so the Spacer in
    // ManageRemindersScreen doesn't overflow in the test harness.
    // tester is passed so we can set the physical size before pumping.
    Widget buildSubject({required List<NavigatorObserver> observers}) {
      return MaterialApp(
        navigatorObservers: observers,
        home: ManageRemindersScreen(
          document: docWithExpiry,
          reminderService: reminderService,
        ),
      );
    }

    // Sets a tall test surface so the Spacer in ManageRemindersScreen doesn't overflow.
    void useTallSurface(WidgetTester tester) {
      tester.view.physicalSize = const Size(1080, 1920);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
    }

    // 1. POST succeeds + GET succeeds → navigates away normally.
    testWidgets('BUG-4: POST+GET both succeed — navigates away', (tester) async {
      useTallSurface(tester);
      int popCount = 0;
      await tester.pumpWidget(buildSubject(observers: [_PopObserver(onPop: () => popCount++)]));
      await tester.pumpAndSettle();

      await tester.tap(find.text('30 days before'));
      await tester.pumpAndSettle();
      await tester.tap(find.text('Save Reminders'));
      await tester.pumpAndSettle();

      expect(reminderService.generateOnlyCallCount, 1);
      expect(popCount, 1);
      expect(find.text('Unable to save reminders'), findsNothing);
    });

    // 2. POST fails → shows "Unable to save reminders", does not navigate away.
    testWidgets('BUG-4: POST fails — shows save failure error', (tester) async {
      useTallSurface(tester);
      reminderService.generateOnlyShouldFail = true;

      await tester.pumpWidget(buildSubject(observers: []));
      await tester.pumpAndSettle();

      await tester.tap(find.text('30 days before'));
      await tester.pumpAndSettle();
      await tester.tap(find.text('Save Reminders'));
      await tester.pumpAndSettle();

      expect(find.text('Unable to save reminders'), findsOneWidget);
    });

    // 3. POST succeeds + GET fails → navigates away (success), no save-failure error.
    testWidgets('BUG-4: POST succeeds GET fails — navigates away, no save error', (tester) async {
      useTallSurface(tester);
      reminderService.getDocumentRemindersShouldFail = true;
      int popCount = 0;

      await tester.pumpWidget(buildSubject(observers: [_PopObserver(onPop: () => popCount++)]));
      await tester.pumpAndSettle();

      await tester.tap(find.text('30 days before'));
      await tester.pumpAndSettle();
      await tester.tap(find.text('Save Reminders'));
      await tester.pumpAndSettle();

      expect(reminderService.generateOnlyCallCount, 1);
      expect(popCount, 1);
      expect(find.text('Unable to save reminders'), findsNothing);
    });

    // 4. GET failure does NOT trigger a second POST.
    testWidgets('BUG-4: GET failure does not cause a second POST', (tester) async {
      useTallSurface(tester);
      reminderService.getDocumentRemindersShouldFail = true;

      await tester.pumpWidget(buildSubject(observers: []));
      await tester.pumpAndSettle();

      await tester.tap(find.text('30 days before'));
      await tester.pumpAndSettle();
      await tester.tap(find.text('Save Reminders'));
      await tester.pumpAndSettle();

      expect(reminderService.generateOnlyCallCount, 1,
          reason: 'POST must be called exactly once regardless of GET outcome');
    });

    // 5. Existing behavior: offset checkboxes toggle correctly.
    testWidgets('BUG-4: existing offset toggle behavior preserved', (tester) async {
      useTallSurface(tester);
      await tester.pumpWidget(buildSubject(observers: []));
      await tester.pumpAndSettle();

      // Tap 30-day checkbox on then off.
      await tester.tap(find.text('30 days before'));
      await tester.pumpAndSettle();
      await tester.tap(find.text('30 days before'));
      await tester.pumpAndSettle();

      // No save attempted, no error shown.
      expect(find.text('Unable to save reminders'), findsNothing);
      expect(reminderService.generateOnlyCallCount, 0);
    });
  });

  group('ReminderItem model', () {
    test('isDue returns true for past dates', () {
      final r = ReminderItem(
        id: '1', documentId: 'd1', documentName: 'x', documentType: 'x',
        title: 'x', reminderDate: DateTime(2020, 1, 1), daysBeforeExpiry: 7,
        status: 'Active', isAutoGenerated: false, createdAt: DateTime(2020),
      );
      expect(r.isDue, isTrue);
    });

    test('isActive returns true for Active status', () {
      final r = ReminderItem(
        id: '1', documentId: 'd1', documentName: 'x', documentType: 'x',
        title: 'x', reminderDate: DateTime(2030, 1, 1), daysBeforeExpiry: 7,
        status: 'Active', isAutoGenerated: false, createdAt: DateTime(2020),
      );
      expect(r.isActive, isTrue);
    });

    test('isActive returns false for Dismissed status', () {
      final r = ReminderItem(
        id: '1', documentId: 'd1', documentName: 'x', documentType: 'x',
        title: 'x', reminderDate: DateTime(2030, 1, 1), daysBeforeExpiry: 7,
        status: 'Dismissed', isAutoGenerated: false, createdAt: DateTime(2020),
      );
      expect(r.isActive, isFalse);
    });
  });
}

// Observes route pops so tests can assert navigation without needing real routes.
class _PopObserver extends NavigatorObserver {
  final void Function() onPop;
  _PopObserver({required this.onPop});

  @override
  void didPop(Route route, Route? previousRoute) => onPop();
}
