using ExpatOne.Application.DTOs;
using ExpatOne.Application.Interfaces;
using ExpatOne.Domain.Entities;
using ExpatOne.Domain.Enums;
using ExpatOne.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace ExpatOne.Infrastructure.Services;

public class ReminderService : IReminderService
{
    private readonly ExpatOneDbContext _dbContext;
    private readonly ILogger<ReminderService> _logger;

    private static readonly int[] DefaultOffsets = [30, 14, 7, 1];

    public ReminderService(ExpatOneDbContext dbContext, ILogger<ReminderService> logger)
    {
        _dbContext = dbContext;
        _logger = logger;
    }

    public async Task<List<ReminderDto>> GetUserRemindersAsync(Guid userId)
    {
        var reminders = await _dbContext.Reminders
            .Include(r => r.Document).ThenInclude(d => d.DocumentType)
            .Where(r => r.UserId == userId && r.Status == ReminderStatus.Active)
            .OrderBy(r => r.ReminderDate)
            .ToListAsync();

        return reminders.Select(MapToDto).ToList();
    }

    public async Task<ReminderDto?> GetReminderAsync(Guid userId, Guid reminderId)
    {
        var reminder = await _dbContext.Reminders
            .Include(r => r.Document).ThenInclude(d => d.DocumentType)
            .FirstOrDefaultAsync(r => r.Id == reminderId && r.UserId == userId);

        return reminder is null ? null : MapToDto(reminder);
    }

    public async Task<ReminderDto> CreateReminderAsync(Guid userId, CreateReminderDto dto)
    {
        var document = await _dbContext.Documents
            .Include(d => d.DocumentType)
            .FirstOrDefaultAsync(d => d.Id == dto.DocumentId && d.UserId == userId)
            ?? throw new KeyNotFoundException("Document not found.");

        if (document.ExpiryDate is null)
            throw new ArgumentException("Document does not have an expiry date.");

        ValidateOffset(dto.DaysBeforeExpiry, document.ExpiryDate.Value);

        var existing = await _dbContext.Reminders
            .AnyAsync(r => r.DocumentId == dto.DocumentId && r.DaysBeforeExpiry == dto.DaysBeforeExpiry
                && r.Status == ReminderStatus.Active);
        if (existing)
            throw new InvalidOperationException("A reminder with this offset already exists for this document.");

        var reminderDate = document.ExpiryDate.Value.AddDays(-dto.DaysBeforeExpiry);

        var reminder = new Reminder
        {
            Id = Guid.NewGuid(),
            UserId = userId,
            DocumentId = dto.DocumentId,
            Title = $"{document.DocumentType.Name} expires in {dto.DaysBeforeExpiry} days",
            Description = $"{document.DocumentName} expires on {document.ExpiryDate.Value:d MMM yyyy}",
            ReminderDate = reminderDate,
            DaysBeforeExpiry = dto.DaysBeforeExpiry,
            IsAutoGenerated = false,
        };

        _dbContext.Reminders.Add(reminder);
        await _dbContext.SaveChangesAsync();

        reminder.Document = document;
        return MapToDto(reminder);
    }

    public async Task<List<ReminderDto>> GenerateRemindersAsync(Guid userId, GenerateRemindersDto dto)
    {
        var document = await _dbContext.Documents
            .Include(d => d.DocumentType)
            .FirstOrDefaultAsync(d => d.Id == dto.DocumentId && d.UserId == userId)
            ?? throw new KeyNotFoundException("Document not found.");

        if (document.ExpiryDate is null)
            throw new ArgumentException("Document does not have an expiry date.");

        var offsets = dto.DaysBeforeExpiry.Count > 0 ? dto.DaysBeforeExpiry : DefaultOffsets.ToList();

        // Cancel existing auto-generated active reminders for this document
        var existingReminders = await _dbContext.Reminders
            .Where(r => r.DocumentId == dto.DocumentId && r.Status == ReminderStatus.Active)
            .ToListAsync();

        foreach (var existing in existingReminders)
        {
            if (!offsets.Contains(existing.DaysBeforeExpiry))
            {
                existing.Status = ReminderStatus.Cancelled;
            }
        }

        var created = new List<Reminder>();
        foreach (var days in offsets)
        {
            if (days <= 0) continue;

            var reminderDate = document.ExpiryDate.Value.AddDays(-days);
            if (reminderDate <= DateTime.UtcNow) continue;

            var alreadyExists = existingReminders.Any(r =>
                r.DaysBeforeExpiry == days && r.Status == ReminderStatus.Active);
            if (alreadyExists) continue;

            var reminder = new Reminder
            {
                Id = Guid.NewGuid(),
                UserId = userId,
                DocumentId = dto.DocumentId,
                Title = $"{document.DocumentType.Name} expires in {days} days",
                Description = $"{document.DocumentName} expires on {document.ExpiryDate.Value:d MMM yyyy}",
                ReminderDate = reminderDate,
                DaysBeforeExpiry = days,
                IsAutoGenerated = true,
            };
            _dbContext.Reminders.Add(reminder);
            created.Add(reminder);
        }

        await _dbContext.SaveChangesAsync();

        foreach (var r in created) r.Document = document;

        _logger.LogInformation("Generated {Count} reminders for document {DocumentId}", created.Count, dto.DocumentId);

        return created.Select(MapToDto).ToList();
    }

    public async Task<ReminderDto> UpdateReminderAsync(Guid userId, Guid reminderId, UpdateReminderDto dto)
    {
        var reminder = await _dbContext.Reminders
            .Include(r => r.Document).ThenInclude(d => d.DocumentType)
            .FirstOrDefaultAsync(r => r.Id == reminderId && r.UserId == userId)
            ?? throw new KeyNotFoundException("Reminder not found.");

        if (dto.Status is not null)
        {
            if (!Enum.TryParse<ReminderStatus>(dto.Status, true, out var newStatus))
                throw new ArgumentException($"Invalid status: {dto.Status}");

            reminder.Status = newStatus;
        }

        await _dbContext.SaveChangesAsync();
        return MapToDto(reminder);
    }

    public async Task DeleteReminderAsync(Guid userId, Guid reminderId)
    {
        var reminder = await _dbContext.Reminders
            .FirstOrDefaultAsync(r => r.Id == reminderId && r.UserId == userId)
            ?? throw new KeyNotFoundException("Reminder not found.");

        _dbContext.Reminders.Remove(reminder);
        await _dbContext.SaveChangesAsync();
    }

    public async Task<List<ReminderDto>> GetDocumentRemindersAsync(Guid userId, Guid documentId)
    {
        var document = await _dbContext.Documents
            .FirstOrDefaultAsync(d => d.Id == documentId && d.UserId == userId)
            ?? throw new KeyNotFoundException("Document not found.");

        var reminders = await _dbContext.Reminders
            .Include(r => r.Document).ThenInclude(d => d.DocumentType)
            .Where(r => r.DocumentId == documentId && r.UserId == userId)
            .OrderBy(r => r.ReminderDate)
            .ToListAsync();

        return reminders.Select(MapToDto).ToList();
    }

    public async Task ProcessDueRemindersAsync()
    {
        var now = DateTime.UtcNow;
        var dueReminders = await _dbContext.Reminders
            .Include(r => r.Document)
            .Where(r => r.Status == ReminderStatus.Active && r.ReminderDate <= now)
            .ToListAsync();

        if (dueReminders.Count == 0) return;

        _logger.LogInformation("Processing {Count} due reminders", dueReminders.Count);

        foreach (var reminder in dueReminders)
        {
            // Notification delivery is deferred — mark as Sent to indicate processed
            reminder.Status = ReminderStatus.Sent;
        }

        await _dbContext.SaveChangesAsync();
        _logger.LogInformation("Processed {Count} reminders", dueReminders.Count);
    }

    private static void ValidateOffset(int daysBeforeExpiry, DateTime expiryDate)
    {
        if (daysBeforeExpiry <= 0)
            throw new ArgumentException("Days before expiry must be positive.");

        var reminderDate = expiryDate.AddDays(-daysBeforeExpiry);
        if (reminderDate <= DateTime.UtcNow)
            throw new ArgumentException("Reminder date would be in the past.");
    }

    private static ReminderDto MapToDto(Reminder r) => new()
    {
        Id = r.Id,
        DocumentId = r.DocumentId,
        DocumentName = r.Document?.DocumentName ?? "",
        DocumentType = r.Document?.DocumentType?.Name ?? "",
        DocumentExpiryDate = r.Document?.ExpiryDate,
        Title = r.Title,
        Description = r.Description,
        ReminderDate = r.ReminderDate,
        DaysBeforeExpiry = r.DaysBeforeExpiry,
        Status = r.Status.ToString(),
        IsAutoGenerated = r.IsAutoGenerated,
        CreatedAt = r.CreatedAt,
    };
}
