using ExpatOne.Domain.Common;
using ExpatOne.Domain.Enums;

namespace ExpatOne.Domain.Entities;

public class Reminder : BaseEntity
{
    public Guid UserId { get; set; }
    public Guid DocumentId { get; set; }
    public required string Title { get; set; }
    public string? Description { get; set; }
    public DateTime ReminderDate { get; set; }
    public int DaysBeforeExpiry { get; set; }
    public ReminderStatus Status { get; set; } = ReminderStatus.Active;
    public bool IsAutoGenerated { get; set; }

    public User User { get; set; } = null!;
    public Document Document { get; set; } = null!;
}
